name: CI/CD Pipeline - Docker Build & Push

on:
  push:
    branches:
      - main  # Exécute l'action quand tu pousses sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise Ubuntu pour construire l’image

    steps:
    # 1. Checkout le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Connexion à Docker Hub avec ton login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build de l’image Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-ci-cd:latest .

    # 4. Push de l’image vers Docker Hub
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-ci-cd:latest
